### ISSUE TITLE
`addOrReplaceObjectAttribute` raises the exception when an property is null

### ISSUE THREAD

**Issue by derevnjuk** [thomaspoignant/scim-patch#186]
**Version**: `0.5.6`

**Description**

When an property is null, `addOrReplaceObjectAttribute` raises the following exception: `Invalid patch query` 

```ts
scimPatch({ externalId: null }, [{ op: "add", path: "externalId", value: "1" }])
```

However, it behaves properly while adding value to undefined property:

```ts
const result = scimPatch({ externalId: undefined }, [{ op: "add", path: "externalId", value: "1" }]);

expect(result).toEqual({ externalId: "1" })
```

**Comment by thomaspoignant** [comment]
Hi @derevnjuk thank you for reporting this issue.
I will review the RFC and the code to validate this issue and get back to you as soon as possible.

**Comment by derevnjuk** [comment]
Hi @thomaspoignant, we have encountered this bug while upgrading to 0.5.6 from 0.5.2. Thanks 😊

**Comment by thomaspoignant** [comment]
Hi @derevnjuk thanks a lot for raising this issue, I have reproduced the problem and opened a PR to fix it (#189).
I will deploy a new version later today.

**Comment by thomaspoignant** [comment]
The version `v0.5.8` is [available](https://npmjs.org/package/scim-patch).

**Comment by derevnjuk** [comment]
@thomaspoignant thanks, it seems it works as expected after the upgrade to 0.5.8
