### ISSUE TITLE
Add/Replace operations with no path but using custom schema attributes do not work

### ISSUE THREAD

**Issue by Francesco-Lanciana** [thomaspoignant/scim-patch#207]
**Describe the bug**
The path parsing when supplying a patch operation with no path but using a custom schema attribute is not correct.

**To Reproduce**
Attempt this patch operation:

```json
        {
            "schemas": [
                "urn:ietf:params:scim:schemas:core:2.0:PatchOp"
            ],
            "Operations":[
                {
                    "op":"replace",
                    "value": {
                        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:organization": "organization",
                        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:department": "department"
                   }
                },
                {
                    "op":"add",
                    "value": {
                        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:division": "division"
                   }
                }
            ]
        }
````
**Expected behavior**
The add and replace operations should work even when using custom schema attributes.

**Additional context**
We are applying to be part of the Azure App Gallery and this was one of the tests that we failed and need to fix in order to be approved.

**Comment by Francesco-Lanciana** [comment]
I've already forked the repo and fixed the issue, will create a PR back into the main branch shortly

**Comment by thomaspoignant** [comment]
Thanks for raising the issue, I will look at your pull request and release a new version if everything is alright.

**Comment by Francesco-Lanciana** [comment]
No problem, thanks for the speedy response! Let me know if I missed anything - can fix it ASAP.
