### ISSUE TITLE
validate should throw an error if a replace operation is called without an value

### ISSUE THREAD

**Issue by soccermax** [thomaspoignant/scim-patch#290]
**Describe the bug**
In my unit-test suite I test my scim service against a various number of invalid patch requests. I just tested my test suite with this node package and encountered that the following call is not rejected even though the following body is not valid IMO. 

**To Reproduce**

Sample request:
```json
{
  "Operations": [
    {
      "op": "replace",
      "path": "displayName"
    }
  ],
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ]
}
```

### expected
the function patchBodyValidation should throw an error.

**Comment by thomaspoignant** [comment]
@soccermax thanks for opening this issue.
I have not much time to work on it for now but if you want to open a pull request to fix it, it would be awesome.

I will get back to it as soon as I have some free time.

**Comment by thomaspoignant** [comment]
Closing the issue for the lack of answer.
