### ISSUE TITLE
Replace op with value of empty object results in circular reference

### ISSUE THREAD

**Issue by blairlunceford** [thomaspoignant/scim-patch#489]
**Describe the bug**
We've seen Azure AD SCIM send replace operations with an empty object in the `value` field:

```
{
  op: 'replace',
  path: 'phoneNumbers[type eq "work"].value',
  value: {},
}
```

They sometimes send this operation when there isn't a multi-valued attribute of that type. When this happens, the `scim-patch` library applies the update in a way that introduces a circular reference to the resource object. This causes errors when we call `JSON.stringify` on the resource object.

**To Reproduce**
```
const scimPatch = require("scim-patch")
const assert = require("assert")

const resource = {
   phoneNumbers: [
    {
      type: 'mobile',
      value: '7865439908',
    },
  ],
}

const operation = {
  op: 'replace',
  path: 'phoneNumbers[type eq "work"].value',
  value: {},
}

const expected = {
  phoneNumbers: [
    {
      type: 'mobile',
      value: '7865439908',
    },
    {
      type: 'work',
      value: {},
    },
  ],
}

const patchedResource = scimPatch.scimPatch(resource, [operation], { mutateDocument: false, treatMissingAsAdd: true },)

assert.deepStrictEqual(patchedResource, expected)

console.log(patchedResource);
=> {
      phoneNumbers: [
        { type: 'mobile', value: '7865439908' },
        { type: 'work', value: [Circular *1] }
      ]
    }
```

**Expected behavior**
We would expect operations to be applied to resources in a way that doesn't introduce a circular reference in the object. Though, admittedly, this update is a bit strange from Azure AD SCIM (the value should be a string here I believe, and this only seems to happen with an empty object).

**Additional context**
We wanted to flag this in the upstream library. We're currently looking at workarounds on our end to either edit the resource before sending it to the library, or checking for circular references when we get the resource from the library.

**Comment by thomaspoignant** [comment]
Hey @blairlunceford thanks for your report, I will release a version `0.8.1` today containing the fix for this issue.

**Comment by thomaspoignant** [comment]
@leonardo-speranzon can you open an issue dedicated to this?
If you want, you can also open a PR to fix the issue.

**Comment by leonardo-speranzon** [comment]
I've opened the issue, I will try to make a PR in the next days
