### ISSUE TITLE
Remove not working properly

### ISSUE THREAD

**Issue by randomhash** [thomaspoignant/scim-patch#54]
**Describe the bug**
Hello, remove value from array leads to clean remove of all items from array

**To Reproduce**
Object to patch
```
{
      schemas: [ 'urn:ietf:params:scim:schemas:core:2.0:Group' ],
      id: 'some-id',
      objectsToPatch: [
        {
          value: 'remove-me',
          display: ''
        },
        {
          value: 'do-not-remove-me',
          display: ''
        }
      ]
    }
```

Operations:

```
[
    {
      op: 'remove',
      path: 'objectsToPatch',
      value: [
        {
          value: 'remove-me',
          display: ''
        }
      ]
    }
  ]
```

**Actual results**
```
{
      schemas: [ 'urn:ietf:params:scim:schemas:core:2.0:Group' ],
      id: 'some-id'
}
```
**Expected behavior**

```
{
      schemas: [ 'urn:ietf:params:scim:schemas:core:2.0:Group' ],
      id: 'some-id',
      objectsToPatch: [
        {
          value: 'do-not-remove-me',
          display: ''
        }
      ]
}
```

**Additional information**

![image](https://user-images.githubusercontent.com/61245342/100272853-7de00300-2f64-11eb-9225-28008d52963f.png)

This part treated by the big SCIM users, as one login, as shown in the example above

**Comment by thomaspoignant** [comment]
Hi @randomhash,
good catch, it seems that this part is missing from this implementation you are right.
I will look at the pull request also to give you some feedback.

**Comment by thomaspoignant** [comment]
The version `v0.4.0` fix this problem and this version is available on npm.
