### ISSUE TITLE
Patch with replace + non-matching filter on a multi-valued attribute does not error

### ISSUE THREAD

**Issue by markwongsk** [thomaspoignant/scim-patch#74]
**Describe the bug**
Currently, when I patch a multi-valued attribute with a valuePath filter that matches nothing, the replacement value gets added as a multi-valued attribute. The SCIM spec details:

>    o  If the target location is a multi-valued attribute for which a
      value selection filter ("valuePath") has been supplied and no
      record match was made, the service provider SHALL indicate failure
      by returning HTTP status code 400 and a "scimType" error code of
      "noTarget".

This is probably due to this line: https://github.com/thomaspoignant/scim-patch/blob/master/src/scimPatch.ts#L194, which I think is misinterpreting complex attribute as a multi-valued attribute.

**To Reproduce**
```
    let group = { id: 'blah', displayName: 'name', members: [] }; // empty SCIM group.
    const op = [
      {   
        op: 'replace',
        path: 'members[value eq "bogus"]',
        value: 'this value should not be added',
      },  
    ];
    const patchedGroup = scimPatch(group, op);
```

**Expected behavior**
a SCIM Error of noTarget 
**Actual behavior**
'this value should not be added' is added as an array value of `group.members`

**Comment by thomaspoignant** [comment]
@markwongsk thanks for reporting this issue.
I've re-read the RFC and I think you are right, we should return a `NoTarget` in that case  and not add the value as it is.

I have open a PR #77, can you look at it and see if it seems ok for you?
If so I will merge it and create a publish a version **`v0.4.3`** with this fix.
